### ISSUE TITLE
[MCOMPILER-179] Warnings 

### ISSUE THREAD

**Issue by olamy** [olamy/maven-compiler-plugin#116]
**[Sascha Vogt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=saschavogt)** opened **[MCOMPILER-179](https://issues.apache.org/jira/browse/MCOMPILER-179?redirect=false)** and commented

If one error occurs, all warnings are shown as error as well. Up to `2.3.2` this was not the case. Sample output `2.4` and higher:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] bad path element "": no such file or directory
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[19,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[ERROR]
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[20,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[ERROR]
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[24,15]
[unchecked] unchecked conversion
found   : java.util.List
required: java.util.List<java.lang.String>
[ERROR]
C:\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[29,29]
getList() in de.maybebuggy.sample.Main cannot be applied to (int)
[INFO] 4 errors
```

Sample output `2.3.2`:

```
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[19,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[WARNING]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[20,18]
[unchecked] unchecked call to add(E) as a member of the raw type
java.util.List
[WARNING]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[24,15]
[unchecked] unchecked conversion
found   : java.util.List
required: java.util.List<java.lang.String>
[INFO] 3 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR]
\dev-tmp\sample\src\main\java\de\maybebuggy\sample\Main.java:[29,29]
getList() in de.maybebuggy.sample.Main cannot be applied to (int)
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

With the current behavior it is extremely hard to spot the error if there are multiple warnings in a project.

---

**Affects:** 2.4, 2.5, 2.5.1

**Issue Links:**
- [MCOMPILER-120](https://issues.apache.org/jira/browse/MCOMPILER-120) Javac compiler plugin doesn't support -Werror

4 votes, 9 watchers

**Comment by olamy** [comment]
**[Sascha Vogt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=saschavogt)** commented

I'm sorry, I missed the settings for the compiler (copied from the effective pom):
\<compilerArgument>-Xlint:all\</compilerArgument>
\<showWarnings>true\</showWarnings>
\<showDeprecation>true\</showDeprecation>
\<compilerVersion>1.6\</compilerVersion>

\<source>1.6\</source>
\<target>1.6\</target>

**Comment by olamy** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

This broke in r1133088, meaning it was broken with the plexus-compiler upgrade

**Comment by olamy** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Fixed in plexus-compiler-javac 1.9.2

**Comment by olamy** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Fixed in r1381893, thanks for the report!

**Comment by olamy** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The fix breaks the IT of MCOMPILER-120, downgrading to plexus-compiler-1.9.1 makes IT succeed again.

**Comment by olamy** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Sorry, that's what I get for fixing a bug when a number of IT's were already failing. I'll look into it.

**Comment by olamy** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

temporarily set plexus-compiler back to 1.9.1

All IT are passing now.

**Comment by olamy** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

`@Kristian`: Did you look into this? Ran into it in a project. It's a nasty one as it's hard to understand that it's a bug in the plugin.

**Comment by olamy** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Yes, we're in the middle of quite a bit of trouble on this one. p-c 1.9.2 "fixes" it but breaks some IT in the compiler-plugin. I have not yet had the chance to investiate exactly why it fails. This code is so brittle I dislike changing it ;)

**Comment by olamy** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

I believe that my fix on plexus-compiler for MCOMPILER-160 also fixes the problem with the IT for MCOMPILER-120. BUT, it's a band-aid fix of the code not being able to parse things correctly.

**Comment by olamy** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

I have now verified that IT for MCOMPILER-120 works with p-c 1.9.3-SNAPSHOT. But it's not really a pretty solution for MCOMPILER-120 as the plugin's error message will say that it couldn't parse the compiler output.

I think that the main problem is that the compilation result (ok/nok) is based on if there's an error message returned. A better solution would be to have a separate result value, and then have debug/warning/error messages for logging only.

**Comment by olamy** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

IT added in http://svn.apache.org/r1407250

**Comment by olamy** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

Rework in upcoming plexus-compiler:2.0 fixes this.

**Comment by olamy** [comment]
**[Eric Sirianni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sirianni)** commented

I am still seeing this issue in maven 3.1.1.  See this [Hadoop JIRA](https://issues.apache.org/jira/browse/HDFS-5462) as an example.
